export const
  PAGES_FETCHED = 'pages.PAGES_FETCHED',
  PAGE_FETCHED = 'pages.PAGE_FETCHED',
  PAGE_EDIT_FAILED = 'pages.PAGE_EDIT_FAILED',
  PAGE_CREATED = 'pages.PAGE_CREATED',
  PAGE_CREATE_FAILED = 'pages.PAGE_CREATE_FAILED',
  CLEAR_CREATE_STATE = 'pages.CLEAR_CREATE_STATE';
